apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: h1jly7knq-nodejs 
  janus-idp.io/tekton: h1jly7knq-nodejs
  backstage.io/kubernetes-id: h1jly7knq-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: h1jly7knq-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml